box: python:2.7
build:
  steps:
    - virtualenv:
        name: setup virtual environment
        install_wheel: false

    - script:
        name: echo python information
        code: |
          echo "python version $(python --version) running"
          echo "pip version $(pip --version) running"
          lscpu
